"""Tests for services/ha_installer.py — Prompt 4 chunks 1.C + 1.D.

Coverage:
  read_current_image     happy path + missing file + 0 / multiple matches
  pin_compose_image      happy path + atomic write + repo mismatch refuses
                         + preserves comments around the image line
  recreate_ha_container  happy + non-zero exit + timeout + docker_not_found
  probe_ha_health        version match on first try + match after retries
                         + version mismatch exhausts attempts
                         + http error / network error retries
                         + malformed JSON retries
  probe_ha_alive         returns on first 200 regardless of version field
  rollback               happy path + compose already at target +
                         recreate failure + probe failure +
                         compose file missing
  apply_manifest         happy path (state.previous_image_tag flow,
                         mark_installed called, previous cleared)
                       + already_at_target (no mutation)
                       + dry_run (no mutation)
                       + invalid manifest shapes
                       + missing compose file (no rollback needed)
                       + compose_pin_failed (no rollback needed; file
                         was atomic)
                       + recreate failure → rollback fires
                       + probe failure → rollback fires
                       + rollback_on_failure=False keeps the failed state
                       + cascading: apply fails AND rollback fails
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Optional

import pytest

from services import ha_installer


# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------

_HA_REPO = "ghcr.io/home-assistant/home-assistant"


def _compose_with(tag: str) -> str:
    """Minimal but realistic compose. Comments around the image line let
    pin_compose_image's "preserves comments" assertion bite."""
    return f"""# Auto-generated by relay/app/provisioner.py
services:
  homeassistant:
    # Pin managed by services/ha_installer.py — do not edit by hand.
    image: {_HA_REPO}:{tag}
    restart: unless-stopped
  ziggy:
    image: registry.fly.io/ziggy:latest
"""


def _settings(compose_file: Path, *, health_url: str = "http://ha.local:8123",
              attempts: int = 2, interval: float = 0.0) -> dict:
    return {
        "home_assistant": {"token": "test-token"},
        "ha": {
            "compose_file":            str(compose_file),
            "image_repo":              _HA_REPO,
            "health_url":              health_url,
            "apply_timeout_s":         30,
            "health_check_attempts":   attempts,
            "health_check_interval_s": interval,
        },
    }


class _FakeResp:
    """requests-shaped fake. status_code + .json() + .text."""
    def __init__(self, status: int, payload=None):
        self.status_code = status
        self._payload = payload
        self.text = json.dumps(payload) if isinstance(payload, dict) else str(payload or "")

    def json(self):
        if isinstance(self._payload, dict):
            return self._payload
        raise ValueError("not json")


class _FakeRun:
    """subprocess.run-shaped fake. Configurable returncode + stderr."""
    def __init__(self, returncode: int = 0, stderr: str = "", stdout: str = "",
                 *, raise_exc: Optional[Exception] = None):
        self.returncode = returncode
        self.stderr = stderr
        self.stdout = stdout
        self.raise_exc = raise_exc
        self.calls: list[list[str]] = []

    def __call__(self, cmd, *, timeout):
        self.calls.append(list(cmd))
        if self.raise_exc is not None:
            raise self.raise_exc
        return subprocess.CompletedProcess(
            cmd, self.returncode, stdout=self.stdout, stderr=self.stderr,
        )


def _redirect_state(monkeypatch, tmp_path) -> Path:
    """Point the module-level installer state file at a temp path."""
    state = tmp_path / "ha_installer_state.json"
    monkeypatch.setattr(ha_installer, "INSTALLER_STATE_PATH", state)
    return state


# ---------------------------------------------------------------------------
# read_current_image
# ---------------------------------------------------------------------------

def test_read_current_image_happy(tmp_path):
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))
    out = ha_installer.read_current_image(f)
    assert out["repo"] == _HA_REPO
    assert out["tag"] == "2026.4.2"


def test_read_current_image_missing(tmp_path):
    with pytest.raises(FileNotFoundError):
        ha_installer.read_current_image(tmp_path / "nope.yml")


def test_read_current_image_zero_matches(tmp_path):
    f = tmp_path / "compose.yml"
    f.write_text("services:\n  homeassistant:\n    image: somewhere/else:1\n")
    with pytest.raises(ValueError, match="No home-assistant image line"):
        ha_installer.read_current_image(f)


def test_read_current_image_multiple_matches(tmp_path):
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("a") + _compose_with("b"))
    with pytest.raises(ValueError, match="Multiple home-assistant image lines"):
        ha_installer.read_current_image(f)


def test_read_current_image_ignores_comments(tmp_path):
    f = tmp_path / "compose.yml"
    f.write_text(
        "# image: ghcr.io/home-assistant/home-assistant:fake-1\n"
        "services:\n  homeassistant:\n"
        f"    image: {_HA_REPO}:real-2\n"
    )
    out = ha_installer.read_current_image(f)
    assert out["tag"] == "real-2"


# ---------------------------------------------------------------------------
# pin_compose_image
# ---------------------------------------------------------------------------

def test_pin_compose_image_happy_preserves_comments(tmp_path):
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))
    out = ha_installer.pin_compose_image(f, _HA_REPO, "2026.5.1")
    assert out == {"from_tag": "2026.4.2", "to_tag": "2026.5.1", "repo": _HA_REPO}
    text = f.read_text()
    assert f"{_HA_REPO}:2026.5.1" in text
    assert f"{_HA_REPO}:2026.4.2" not in text
    # Comments + sibling service still present
    assert "# Auto-generated by relay/app/provisioner.py" in text
    assert "# Pin managed by services/ha_installer.py" in text
    assert "registry.fly.io/ziggy:latest" in text


def test_pin_compose_image_refuses_repo_mismatch(tmp_path):
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))
    with pytest.raises(ValueError, match="Refusing to swap repositories"):
        ha_installer.pin_compose_image(f, "ghcr.io/other/home-assistant", "2026.5.1")
    # File unchanged
    assert f"{_HA_REPO}:2026.4.2" in f.read_text()


def test_pin_compose_image_atomic_no_tmp_left(tmp_path):
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))
    ha_installer.pin_compose_image(f, _HA_REPO, "2026.5.1")
    leftovers = list(tmp_path.glob("*.tmp"))
    assert not leftovers, f"tmp files not cleaned: {leftovers}"


# ---------------------------------------------------------------------------
# recreate_ha_container
# ---------------------------------------------------------------------------

def test_recreate_ok(tmp_path):
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))
    fake = _FakeRun(returncode=0, stdout="Recreated\n")
    r = ha_installer.recreate_ha_container(f, _run_cmd=fake)
    assert r["ok"] is True
    assert r["reason"] == "recreated"
    # Confirm we shelled out the right command shape
    assert fake.calls[0][:4] == ["docker", "compose", "-f", str(f)]
    assert fake.calls[0][-3:] == ["up", "-d", "homeassistant"]


def test_recreate_non_zero_exit(tmp_path):
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))
    fake = _FakeRun(returncode=1, stderr="Error: image not found")
    r = ha_installer.recreate_ha_container(f, _run_cmd=fake)
    assert r["ok"] is False
    assert r["reason"] == "docker_non_zero"
    assert "image not found" in r["detail"]


def test_recreate_timeout(tmp_path):
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))
    fake = _FakeRun(raise_exc=subprocess.TimeoutExpired(cmd="docker", timeout=1))
    r = ha_installer.recreate_ha_container(f, _run_cmd=fake, timeout_s=1)
    assert r["ok"] is False
    assert r["reason"] == "docker_timeout"


def test_recreate_docker_not_found(tmp_path):
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))
    fake = _FakeRun(raise_exc=FileNotFoundError())
    r = ha_installer.recreate_ha_container(f, _run_cmd=fake)
    assert r["ok"] is False
    assert r["reason"] == "docker_not_found"


def test_recreate_compose_missing(tmp_path):
    fake = _FakeRun(returncode=0)
    r = ha_installer.recreate_ha_container(tmp_path / "absent.yml", _run_cmd=fake)
    assert r["ok"] is False
    assert r["reason"] == "compose_file_missing"
    assert fake.calls == []  # docker never called


# ---------------------------------------------------------------------------
# probe_ha_health (version-equality variant)
# ---------------------------------------------------------------------------

def test_probe_version_match_first_try():
    calls: list[int] = []
    def fake_get(url, headers=None, timeout=None):
        calls.append(1)
        return _FakeResp(200, {"version": "2026.5.1"})
    r = ha_installer.probe_ha_health(
        "http://ha", "2026.5.1", attempts=3, interval_s=0.0,
        _http_get=fake_get, _sleep=lambda s: None,
    )
    assert r["ok"] is True
    assert r["actual_version"] == "2026.5.1"
    assert r["attempts_made"] == 1
    assert len(calls) == 1


def test_probe_version_match_after_retries():
    seq = [
        _FakeResp(503),
        _FakeResp(200, {"version": "2026.4.2"}),    # old version on first 200
        _FakeResp(200, {"version": "2026.5.1"}),
    ]
    i = iter(seq)
    r = ha_installer.probe_ha_health(
        "http://ha", "2026.5.1", attempts=5, interval_s=0.0,
        _http_get=lambda *a, **kw: next(i),
        _sleep=lambda s: None,
    )
    assert r["ok"] is True
    assert r["attempts_made"] == 3


def test_probe_version_mismatch_exhausts():
    r = ha_installer.probe_ha_health(
        "http://ha", "2026.5.1", attempts=3, interval_s=0.0,
        _http_get=lambda *a, **kw: _FakeResp(200, {"version": "2026.4.2"}),
        _sleep=lambda s: None,
    )
    assert r["ok"] is False
    assert "version_mismatch" in r["reason"]
    assert r["attempts_made"] == 3
    assert r["actual_version"] == "2026.4.2"


def test_probe_network_error_retries():
    counts = {"n": 0}
    def fake(*a, **kw):
        counts["n"] += 1
        if counts["n"] < 3:
            raise ConnectionError("boom")
        return _FakeResp(200, {"version": "x"})
    r = ha_installer.probe_ha_health(
        "http://ha", "x", attempts=5, interval_s=0.0,
        _http_get=fake, _sleep=lambda s: None,
    )
    assert r["ok"] is True
    assert r["attempts_made"] == 3


def test_probe_malformed_json_retries_then_fails():
    r = ha_installer.probe_ha_health(
        "http://ha", "x", attempts=2, interval_s=0.0,
        _http_get=lambda *a, **kw: _FakeResp(200, "not-a-dict"),
        _sleep=lambda s: None,
    )
    assert r["ok"] is False
    assert r["attempts_made"] == 2


# ---------------------------------------------------------------------------
# probe_ha_alive (liveness variant — used by rollback)
# ---------------------------------------------------------------------------

def test_probe_alive_returns_on_first_200():
    r = ha_installer.probe_ha_alive(
        "http://ha", attempts=5, interval_s=0.0,
        _http_get=lambda *a, **kw: _FakeResp(200, {"version": "anything"}),
        _sleep=lambda s: None,
    )
    assert r["ok"] is True
    assert r["attempts_made"] == 1
    assert r["actual_version"] == "anything"


def test_probe_alive_keeps_retrying_503():
    r = ha_installer.probe_ha_alive(
        "http://ha", attempts=3, interval_s=0.0,
        _http_get=lambda *a, **kw: _FakeResp(503),
        _sleep=lambda s: None,
    )
    assert r["ok"] is False
    assert r["attempts_made"] == 3


# ---------------------------------------------------------------------------
# rollback
# ---------------------------------------------------------------------------

def test_rollback_happy_rewrites_and_recreates(tmp_path, monkeypatch):
    _redirect_state(monkeypatch, tmp_path)
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.5.1"))   # currently at "new"
    settings = _settings(f)
    fake_run = _FakeRun(returncode=0)
    r = ha_installer.rollback(
        "2026.4.2", settings=settings,
        _run_cmd=fake_run,
        _http_get=lambda *a, **kw: _FakeResp(200, {"version": "2026.4.2"}),
        _sleep=lambda s: None,
    )
    assert r["ok"] is True
    assert r["restored_tag"] == "2026.4.2"
    assert f"{_HA_REPO}:2026.4.2" in f.read_text()
    assert len(fake_run.calls) == 1


def test_rollback_already_at_target_still_runs_recreate(tmp_path, monkeypatch):
    _redirect_state(monkeypatch, tmp_path)
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))   # already at target
    fake_run = _FakeRun(returncode=0)
    r = ha_installer.rollback(
        "2026.4.2", settings=_settings(f),
        _run_cmd=fake_run,
        _http_get=lambda *a, **kw: _FakeResp(200, {"version": "2026.4.2"}),
        _sleep=lambda s: None,
    )
    assert r["ok"] is True
    assert len(fake_run.calls) == 1  # re-runs docker compose to converge


def test_rollback_recreate_failure(tmp_path, monkeypatch):
    state = _redirect_state(monkeypatch, tmp_path)
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.5.1"))
    r = ha_installer.rollback(
        "2026.4.2", settings=_settings(f),
        _run_cmd=_FakeRun(returncode=1, stderr="boom"),
        _http_get=lambda *a, **kw: _FakeResp(200),
        _sleep=lambda s: None,
    )
    assert r["ok"] is False
    assert "recreate_failed" in r["reason"]
    saved = json.loads(state.read_text())
    assert "rollback_failed" in saved["last_apply_outcome"]


def test_rollback_probe_failure(tmp_path, monkeypatch):
    state = _redirect_state(monkeypatch, tmp_path)
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.5.1"))
    r = ha_installer.rollback(
        "2026.4.2", settings=_settings(f),
        _run_cmd=_FakeRun(returncode=0),
        _http_get=lambda *a, **kw: _FakeResp(500),
        _sleep=lambda s: None,
    )
    assert r["ok"] is False
    assert "probe_failed" in r["reason"]


def test_rollback_compose_file_missing(tmp_path, monkeypatch):
    _redirect_state(monkeypatch, tmp_path)
    f = tmp_path / "nope.yml"
    r = ha_installer.rollback("any", settings=_settings(f))
    assert r["ok"] is False
    assert r["reason"] == "compose_file_missing"


# ---------------------------------------------------------------------------
# apply_manifest
# ---------------------------------------------------------------------------

def _manifest(version: str = "2026.5.1", release_id: int = 7) -> dict:
    return {
        "release_id":    release_id,
        "ha_version":    version,
        "ziggy_version": "1.2.3",
        "image_digests": {},
        "schema_version": 1,
    }


def test_apply_happy_path(tmp_path, monkeypatch):
    state_path = _redirect_state(monkeypatch, tmp_path)
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))
    seen_marked: list[dict] = []

    r = ha_installer.apply_manifest(
        _manifest("2026.5.1"),
        settings=_settings(f),
        _run_cmd=_FakeRun(returncode=0),
        _http_get=lambda *a, **kw: _FakeResp(200, {"version": "2026.5.1"}),
        _sleep=lambda s: None,
        _mark_installed=lambda m: seen_marked.append(m),
    )
    assert r["ok"] is True
    assert r["reason"] == "installed"
    assert r["from_version"] == "2026.4.2"
    assert r["to_version"] == "2026.5.1"
    assert r["rolled_back"] is False
    assert seen_marked and seen_marked[0]["release_id"] == 7
    # Compose actually pinned
    assert f"{_HA_REPO}:2026.5.1" in f.read_text()
    # Installer state: previous cleared after success
    saved = json.loads(state_path.read_text())
    assert saved["previous_image_tag"] is None
    assert "installed" in saved["last_apply_outcome"]


def test_apply_already_at_target_no_mutation(tmp_path, monkeypatch):
    _redirect_state(monkeypatch, tmp_path)
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.5.1"))
    fake_run = _FakeRun(returncode=0)
    r = ha_installer.apply_manifest(
        _manifest("2026.5.1"),
        settings=_settings(f),
        _run_cmd=fake_run,
    )
    assert r["ok"] is True
    assert r["reason"] == "already_at_target"
    assert fake_run.calls == []  # never even tried docker


def test_apply_dry_run_does_not_mutate(tmp_path, monkeypatch):
    _redirect_state(monkeypatch, tmp_path)
    f = tmp_path / "compose.yml"
    original = _compose_with("2026.4.2")
    f.write_text(original)
    fake_run = _FakeRun(returncode=0)
    r = ha_installer.apply_manifest(
        _manifest("2026.5.1"),
        settings=_settings(f),
        dry_run=True,
        _run_cmd=fake_run,
    )
    assert r["ok"] is True
    assert r["reason"] == "dry_run"
    assert f.read_text() == original
    assert fake_run.calls == []


def test_apply_invalid_manifest_not_dict():
    r = ha_installer.apply_manifest("not a dict")  # type: ignore[arg-type]
    assert r["ok"] is False
    assert r["reason"] == "invalid_manifest"


def test_apply_invalid_manifest_missing_keys(tmp_path):
    r = ha_installer.apply_manifest({"foo": "bar"})
    assert r["ok"] is False
    assert r["reason"] == "invalid_manifest"


def test_apply_compose_missing(tmp_path, monkeypatch):
    _redirect_state(monkeypatch, tmp_path)
    r = ha_installer.apply_manifest(
        _manifest(),
        settings=_settings(tmp_path / "absent.yml"),
    )
    assert r["ok"] is False
    assert r["reason"] == "compose_file_missing"
    assert r["rolled_back"] is False   # nothing mutated, nothing to revert


def test_apply_recreate_failure_triggers_rollback(tmp_path, monkeypatch):
    _redirect_state(monkeypatch, tmp_path)
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))

    # First call (apply's `up -d`) fails; second call (rollback's `up -d`)
    # succeeds. _FakeRun returns the same code each call, so use a counter.
    calls = {"n": 0}
    def fake_run(cmd, *, timeout):
        calls["n"] += 1
        rc = 1 if calls["n"] == 1 else 0
        return subprocess.CompletedProcess(cmd, rc, stdout="", stderr="boom")

    # Health probe is irrelevant for apply (recreate fails first) but
    # rollback's alive-probe must succeed.
    r = ha_installer.apply_manifest(
        _manifest("2026.5.1"),
        settings=_settings(f),
        _run_cmd=fake_run,
        _http_get=lambda *a, **kw: _FakeResp(200, {"version": "2026.4.2"}),
        _sleep=lambda s: None,
    )
    assert r["ok"] is False
    assert "recreate_failed" in r["reason"]
    assert r["rolled_back"] is True
    # Compose reverted
    assert f"{_HA_REPO}:2026.4.2" in f.read_text()


def test_apply_probe_failure_triggers_rollback(tmp_path, monkeypatch):
    _redirect_state(monkeypatch, tmp_path)
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))

    # docker compose always succeeds. Apply's version probe never matches
    # the new version. Rollback's alive probe returns 200.
    def fake_get(url, headers=None, timeout=None):
        # Always return the OLD version — apply expects new and never sees it
        return _FakeResp(200, {"version": "2026.4.2"})

    r = ha_installer.apply_manifest(
        _manifest("2026.5.1"),
        settings=_settings(f, attempts=2, interval=0.0),
        _run_cmd=_FakeRun(returncode=0),
        _http_get=fake_get,
        _sleep=lambda s: None,
    )
    assert r["ok"] is False
    assert "health_probe_failed" in r["reason"]
    assert r["rolled_back"] is True
    assert f"{_HA_REPO}:2026.4.2" in f.read_text()


def test_apply_rollback_disabled_keeps_failed_state(tmp_path, monkeypatch):
    _redirect_state(monkeypatch, tmp_path)
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))

    r = ha_installer.apply_manifest(
        _manifest("2026.5.1"),
        settings=_settings(f, attempts=1, interval=0.0),
        rollback_on_failure=False,
        _run_cmd=_FakeRun(returncode=0),
        _http_get=lambda *a, **kw: _FakeResp(200, {"version": "2026.4.2"}),
        _sleep=lambda s: None,
    )
    assert r["ok"] is False
    assert r["rolled_back"] is False
    # Compose still has the NEW tag — failure not reverted
    assert f"{_HA_REPO}:2026.5.1" in f.read_text()


def test_apply_cascading_rollback_failure(tmp_path, monkeypatch):
    """Apply fails AND rollback fails — rolled_back=False, reason
    surfaces the original apply failure, detail carries the rollback err."""
    _redirect_state(monkeypatch, tmp_path)
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))

    # All docker compose calls fail. So apply's recreate fails, then
    # rollback's recreate also fails.
    r = ha_installer.apply_manifest(
        _manifest("2026.5.1"),
        settings=_settings(f),
        _run_cmd=_FakeRun(returncode=1, stderr="docker dead"),
        _http_get=lambda *a, **kw: _FakeResp(200, {"version": "2026.4.2"}),
        _sleep=lambda s: None,
    )
    assert r["ok"] is False
    assert "recreate_failed" in r["reason"]
    assert r["rolled_back"] is False
    assert "rollback: ok=False" in r["detail"]


def test_apply_persists_previous_image_tag_before_mutation(tmp_path, monkeypatch):
    """Crash-safety: state.previous_image_tag is written BEFORE compose
    is mutated. We verify by injecting a pin failure and confirming the
    state file still records the previous tag."""
    state_path = _redirect_state(monkeypatch, tmp_path)
    f = tmp_path / "compose.yml"
    f.write_text(_compose_with("2026.4.2"))

    # Force pin_compose_image to fail AFTER load_state already ran.
    def boom(*a, **kw):
        raise ValueError("simulated pin failure")
    monkeypatch.setattr(ha_installer, "pin_compose_image", boom)

    r = ha_installer.apply_manifest(
        _manifest("2026.5.1"),
        settings=_settings(f),
        _run_cmd=_FakeRun(returncode=0),
    )
    assert r["ok"] is False
    assert r["reason"] == "compose_pin_failed"
    saved = json.loads(state_path.read_text())
    assert saved["previous_image_tag"] == "2026.4.2"
    assert saved["last_apply_outcome"] in (
        "failed_no_rollback: compose_pin_failed",
        "in_progress",   # tolerant — sequencing detail
    )
