openai:
  api_key: "your-openai-api-key-here"

audio:
  ffplay_path: "ffplay"

voice:
  wakeword_enabled: false

telegram:
  bot_token: "your-telegram-bot-token-here"
  token: "your-telegram-bot-token-here"
  chat_id: "your-telegram-chat-id-here"

home_assistant:
  url: "http://homeassistant.local:8123/"
  token: "your-home-assistant-token-here"

mqtt:
  host: "localhost"
  port: 1883
  username: ""
  password: ""

features:
  voice: false
  zigbee_support: false
  telegram: false

debug:
  enable_dashboard: true
  verbose_logging: true

database:
  url: "mongodb://localhost:27017"
  name: "ziggy_web"

web_interface:
  backend_port: 8001
  frontend_port: 3000