assistant_name: Ziggy
bsd: bsdbs
favorite_color: warm yellow
home_assistant:
  url: http://homeassistant.local:8123/
home_city: Binyamina
home_country: Israel
home_timezone: Asia/Jerusalem
identity: i am the king
language: English
my dog: the worst
test_key: test_value
user_name: Youval
wake_word: ziggy
