assistant_name: Ziggy
home_assistant:
  url: http://homeassistant.local:8123/
home_city: Binyamina
home_country: Israel
home_timezone: Asia/Jerusalem
language: English
my dog: Mika
user_name: Youval
wake_word: hey ziggy
wife: Adi
